version: '3'

services:
    apache1:
          container_name: apache_1 
          image: omar9289/apache 
          ports:
            - 9090:8080

    apache2:
          container_name: apache_2
          ports:
            - 8080:8080
          build:
            context: ./App2/
            dockerfile: Dockerfile

    reverse_proxy:
          container_name: reverse_proxy
          build: .
          ports:
            - 80:80
