version: '3.2'
services:
  jenkins:
    image: jenkins/jenkins
    volumes:
      - ./jenkins:/var/jenkins_home:rw
      - ./war:/mnt/:rw    # from jenkins >> execute shell >> cp target/*.war /mnt >> {1}
    ports:
      - 8080:8080
    container_name: jenkins
    
  tomcat:
    image: mzain/tomcat
    ports:
      - 7777:8080
    container_name: tomcat
    depends_on:
      - jenkins
    volumes:
       - ./war/:/usr/local/tomcat/webapps     # /usr/local/tomcat/ = $(CATALINA_HOME), in this path , will deploy a new pkg (*.war) >> {2}
